### ISSUE TITLE
v25i board , secplusv1. esphome gui works 100%, and status is updated 100% but homebridge open and close the door stops after 1 second

### ISSUE THREAD

**Issue by jheidecker** [hjdhjd/homebridge-ratgdo#11]
### Homebridge Ratgdo

2.2.2

### Homebridge Platform and OS

Ubuntu Jammy (22.04.4 LTS)

### Homebridge Version

1.8.2

### Node Version

20.14.0

### Ratgdo ESPHome Firmware Version

2024.4.2

### Describe the problem

When opening or closing in HomeKit or in Homebridge APP, the door starts opening but then stops after 1 second.

### Homebridge HBR JSON configuration

```json
{
    "debug": true,
    "name": "Ratgdo",
    "options": [
        "Disable.Motion"
    ],
    "_bridge": {
        "username": "0E:8A:DD:19:93:18",
        "port": 46888
    },
    "platform": "Ratgdo"
}
```

### Relevant log output

```shell
HOMEBRIDGE LOG:

[2024-06-08, 4:41:48 p.m.] [Ratgdo] Garage Door: User-initiated door state change: open.
[2024-06-08, 4:41:48 p.m.] [Ratgdo] Garage Door: User-initiated door state change: open.
[2024-06-08, 4:41:50 p.m.] [Ratgdo] Garage Door: State event received:  '{"id":"cover-door","value":0,"state":"CLOSED","current_operation":"IDLE","position":0}'
[2024-06-08, 4:41:50 p.m.] [Ratgdo] Garage Door: Door state: 0% open.
[2024-06-08, 4:41:50 p.m.] [Ratgdo] Garage Door: State event received:  '{"id":"light-light","state":"ON","color_mode":"onoff","color":{}}'
[2024-06-08, 4:41:50 p.m.] [Ratgdo] Garage Door: Light on.

WEBESP LOG:

16:43:44	[D]	[ratgdo:100]	
Door state=STOPPED
16:43:44	[D]	[ratgdo:209]	
Light state=ON
16:43:44	[D]	[ratgdo:215]	
Lock state=UNLOCKED
16:43:45	[D]	[ratgdo:100]	
Door state=STOPPED
16:43:45	[D]	[ratgdo:209]	
Light state=ON
16:43:45	[D]	[ratgdo:215]	
Lock state=UNLOCKED
16:43:46	[D]	[ratgdo:100]	
Door state=STOPPED
16:43:46	[D]	[ratgdo:209]	
Light state=ON
16:43:46	[D]	[ratgdo:215]	
Lock state=UNLOCKED
16:43:46	[D]	[ratgdo:100]	
Door state=STOPPED
16:43:47	[D]	[ratgdo:209]	
Light state=ON
16:43:47	[D]	[ratgdo:215]	
Lock state=UNLOCKED
16:43:47	[D]	[ratgdo:100]	
Door state=STOPPED
16:43:47	[D]	[ratgdo:209]	
Light state=ON
16:43:47	[D]	[ratgdo:215]
```

### Acknowledgment that you are only running non-beta firmware releases from Apple, ESPHome, or Ratgdo

- [X] I acknowledge that I am not running any beta firmwares or operating systems from Apple, ESPHome, or Ratgdo.

**Comment by hjdhjd** [comment]
HBR is a reflection of what’s going on in the Ratgdo device. If you can fully open and fully close your door opener using the Ratgdo webUI (e.g. http://IP.OF.YOUR.RATGDO), you should be able to in HBR. What you pasted shows that the issue is somewhere between Ratgdo and your garage door opener…I’d focus over there. HBR’s just showing you what Ratgdo is showing you…I’m afraid that the Ratgdo itself is beyond the scope of the support I provide.

**Comment by jheidecker** [comment]
That’s just it though. It DOES work fine from the ratgdo web. That’s why I suspect something between HomeKit <> HomeBridge <> plugin. I have a sec 2.0 ratgdo that DOES work, but 2 sec 1.0 that don’t (from HomeKit/hbr)

**Comment by hjdhjd** [comment]
What you posted would indicate otherwise. It shows your door in a stopped state after a second or so. Did you follow the directions in the HBR documentation directing you to fully open and then fully close the door through a single cycle the first time after had a fully reset ratgdo? Post a screenshot of the complete ratgdo webUI please and I’ll take a look and see if there’s anything that appears obviously off. Beyond that, I don’t see any issues here for HBR.

Happy to take a look.
