### ISSUE TITLE
Allow ESPhome to have Web Auth

### ISSUE THREAD

**Issue by gokou340** [hjdhjd/homebridge-ratgdo#25]
### Describe the feature request

I currently have my Ratgdo flashed with ESPhome, but I didn't want to leave the webpage wide open, so I put an authentication requirement. This causes "401 Unauthorized" within Homebridge.

### Describe the proposed solution

Is it possible to allow users to specify a username and password for authenticating to the Ratgdo device?

### Describe alternatives you have considered to the enhancement

Removed authentication from web server in ESPhome.

**Comment by hjdhjd** [comment]
I appreciate the request, but I have no plans to implement this anytime soon at this time. If you're that concerned about security, you can wall it off in its own subnet/VLAN and only allow access from the device that you're running Homebridge on.

I should add, from a security perspective, you aren't gaining much in adding a username/password here since anyone who has compromised your network can already sniff traffic and will be able to easily deduce them given they are being passed in the clear. ESPHome doesn't currently natively support HTTPS/TLS for the web_server component...your best bet to do something like this is a reverse proxy or network segregation as I described above.
